### ISSUE TITLE
No exit condition following page count error.

### ISSUE THREAD

**Issue by kvoss-teacher** [sheamusburns/veracross#1]
The bit of code below sometimes reports that the 'pages' variable = NaN. There is no error trapping for that possibility, so the loop that follows has no exit condition.
`var initReq = https.get(options(), function(res) {`
`xTotal = res.headers['x-total-count'];`
`pages = Math.ceil(xTotal / countPerPage());`
`console.log('GET: num of calls to make:', pages);`

**Comment by kvoss-teacher** [comment]
By the way, what is the purpose of declaring 'var initReq' in the code?

**Comment by sheamusburns** [comment]
I'll take a look at adding some error handling in there. 

I think the purpose of `var initReq` was simply to have a name attached to the get request so I could tell what it was being used for --- the purpose of that get was only to get the initial values `xTotal` and `pages` needed for the subsequent loop to run properly.

**Comment by sheamusburns** [comment]
Error handling added.
